djangolope/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('servalope.urls'))
]

servalope/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from servalope.views import *

app_name = 'servalope'
urlpatterns = [
    url(r'^mailings/$', login_required(MailingListView.as_view()),name="mailing-list"),
    url(r'^mailings/create$', login_required(CreateMailing.as_view()),name="create-mailing"),
    url(r'^mailings/(?P<pk>[0-9])+/$', login_required(MailingDetailView.as_view()),name="mailing"),
    url(r'^mailings/add-guest$', login_required(AddGuest.as_view()),name="add-guest"),
    url(r'^accounts/register$',RegisterView.as_view(),name='register'),
    url('^accounts/', include('django.contrib.auth.urls')),
    # url(r'^$', views.index, name='index'),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^', login_required(MailingListView.as_view()),name="index"),
]

servalope/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
import datetime

from django.db import models

# Create your models here.

class Mailing(models.Model):
    """Represents an event"""
    name = models.CharField(max_length=100)
    date = models.DateField(default=datetime.datetime.today)
    message = models.CharField(blank=True, max_length=100)
    customer = models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    def __unicode__(self):
        return self.name

class Guest(models.Model):
    """Represents a guest of a given mailing"""
    RSVP_CHOICES = (
        ('Y','Yes'),
        ('M','Maybe'),
        ('N','No'),
    )

    first = models.CharField(blank=True, max_length=100)
    middle = models.CharField(blank=True, max_length=100)
    last = models.CharField(blank=True, max_length=100)
    email = models.EmailField()
    mailing = models.ForeignKey(Mailing,on_delete=models.CASCADE)
    rsvp = models.CharField(choices=RSVP_CHOICES,max_length=1)

    def __unicode__(self):
        return self.first + self.last

servalope/forms.py
from django.forms import Form, ModelForm
from django import forms
from servalope.models import *

class RegisterForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'first_name',
            'last_name',
            'email',
            # 'is_staff',
        ]

class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        fields = [
            'name',
            'date',
            'message'
        ]

class GuestForm(ModelForm):
    class Meta:
        model = Guest
        fields = [
            'first',
            'middle',
            'last',
            'email',
            'mailing',
            'rsvp'
        ]

servalope/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from servalope.models import *
from django.contrib.auth import logout, views as auth_views
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_POST
from django import forms

from servalope.forms import *

# Create your views here.
class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        clean = form.cleaned_data
        u = clean['username']
        p = clean['password']
        e = clean['email']
        user = User.objects.create_user(u,e,p)
        user.first_name = clean['first_name']
        user.last_name = clean['last_name']
        user.save()

        return super(RegisterView, self).form_valid(form)

class CreateMailing(FormView):
    form_class = MailingForm
    success_url = '/mailings/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        clean = form.cleaned_data
        n = clean['name']
        d = clean['date']
        m = clean['message']
        c = self.request.user
        mailing = Mailing(name=n,date=d,message=m,customer=c)
        mailing.save()

        return super(CreateMailing, self).form_valid(form)

class MailingListView(ListView):
    """Displays a list of mailings for a given user"""

    model = Mailing

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(MailingListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_staff or user.is_superuser:
            print('Show all Mailings')
            context['mailing_list'] = Mailing.objects.all()
        else:
            context['mailing_list'] = Mailing.objects.filter(customer=user)

        context['create_form'] = MailingForm()

        return context

class AddGuest(FormView):
    form_class = GuestForm
    success_url = '/mailings/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        clean = form.cleaned_data
        f = clean['first']
        m = clean['middle']
        l = clean['last']
        e = clean['email']
        mailing = clean['mailing']
        rsvp = clean['rsvp']
        guest = Guest(first=f,middle=m,last=l,email=e,mailing=mailing,rsvp=rsvp)
        guest.save()

        return super(AddGuest, self).form_valid(form)

class MailingDetailView(DetailView):
    """Displays the guests and RSVP status for a given mailing"""

    model = Mailing

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(MailingDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['guest_list'] = Guest.objects.filter(mailing=context['mailing'])
        guest_form = GuestForm()
        guest_form.fields['mailing'].widget = forms.HiddenInput()
        guest_form.fields['mailing'].initial = context['mailing']
        context['create_form'] = guest_form

        return context

servalope/templates/servalope/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Servalope | {% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'foundation/css/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'foundation/css/app.css' %}">
  </head>
  <body>
    <div class="row">
      <div class="large-12 columns">
        {% if user.is_authenticated %}
          <h1>Welcome to Servalope, {{ user.username }}!</h1>
          <a href="{% url 'servalope:logout' %}">Log Out</a>
          {% if user.is_superuser %}
          <p>
            As a staff member, you'll be able to see all mailings, even the ones that others create.  You can also access the <a href="/admin">admin site</a> to create, update, or remove entries from mailings, guests, and users.
          </p>
          {% endif %}
        {% else %}
          <h1>Welcome to Servalope!</h1>
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        {% block content %}
        No content
        {% endblock %}
      </div>
    </div>

    <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'foundation/js/vendor/what-input.js' %}"></script>
    <script src="{% static 'foundation/js/vendor/foundation.js' %}"></script>
    <script src="{% static 'foundation/js/vendor/app.js' %}"></script>
    {% block script %}{% endblock %}

  </body>
</html>

servalope/templates/servalope/mailing_detail.html
{% extends "servalope/base.html" %}

{% block title %}
  {{mailing.name}}
{% endblock %}

{% block content %}
  <h2>{{ mailing.name }}</h2>
  <a href="{% url 'servalope:mailing-list' %}">Go back</a>
  <h2>Guest List</h2>
  <div class="row">
    <div class="large-4 columns">
      <form action="{% url 'servalope:add-guest' %}" method="post">
        {% csrf_token %}
        {{ create_form }}
        <input type="submit" value="Add a guest">
      </form>
    </div>
    <div class="large-8 columns">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>RSVP</th>
          </tr>
        </thead>
        <tbody>
          {% for guest in guest_list %}
          <tr>
            <td>{{ guest.first }} {{ guest.middle }} {{ guest.last }}</td>
            <td>{{ guest.email }}</td>
            <td>{{ guest.get_rsvp_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

servalope/templates/servalope/mailing_list.html
{% extends "servalope/base.html" %}

{% block title %}
  Mailings
{% endblock %}

{% block content %}
  <h2>Mailing List</h2>

  <div class="row">
    <div class="large-4 columns">
      <form action="{% url 'servalope:create-mailing' %}" method="post">
        {% csrf_token %}
        {{ create_form }}
        <input type="submit" value="Create a new Mailing">
      </form>
    </div>
    <div class="large-8 columns">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Message</th>
            <th>Customer</th>
          </tr>
        </thead>
        <tbody>
          {% for mailing in mailing_list %}
          <tr>
            <td><a href="{% url 'servalope:mailing' mailing.id %}">{{ mailing.name }}</a></td>
            <td>{{ mailing.date }}</td>
            <td>{{ mailing.message }}</td>
            <td>{{ mailing.customer }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

servalope/templates/servalope/theme.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foundation for Sites</title>
    <link rel="stylesheet" href="{% static 'foundation/css/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'foundation/css/app.css' %}">
  </head>
  <body>
    <div class="row">
      <div class="large-12 columns">
        <h1>Welcome to Foundation</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout">
          <h3>We&rsquo;re stoked you want to try Foundation! </h3>
          <p>To get going, this file (index.html) includes some basic styles you can modify, play around with, or totally destroy to get going.</p>
          <p>Once you've exhausted the fun in this document, you should check out:</p>
          <div class="row">
            <div class="large-4 medium-4 columns">
              <p><a href="http://foundation.zurb.com/docs">Foundation Documentation</a><br />Everything you need to know about using the framework.</p>
            </div>
            <div class="large-4 medium-4 columns">
              <p><a href="http://zurb.com/university/code-skills">Foundation Code Skills</a><br />These online courses offer you a chance to better understand how Foundation works and how you can master it to create awesome projects.</p>
            </div>
            <div class="large-4 medium-4 columns">
              <p><a href="http://foundation.zurb.com/forum">Foundation Forum</a><br />Join the Foundation community to ask a question or show off your knowlege.</p>
            </div>
          </div>
          <div class="row">
            <div class="large-4 medium-4 medium-push-2 columns">
              <p><a href="http://github.com/zurb/foundation">Foundation on Github</a><br />Latest code, issue reports, feature requests and more.</p>
            </div>
            <div class="large-4 medium-4 medium-pull-2 columns">
              <p><a href="https://twitter.com/ZURBfoundation">@zurbfoundation</a><br />Ping us on Twitter if you have questions. When you build something with this we'd love to see it (and send you a totally boss sticker).</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="large-8 medium-8 columns">
        <h5>Here&rsquo;s your basic grid:</h5>
        <!-- Grid Example -->

        <div class="row">
          <div class="large-12 columns">
            <div class="primary callout">
              <p><strong>This is a twelve column section in a row.</strong> Each of these includes a div.callout element so you can see where the columns are - it's not required at all for the grid.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-6 medium-6 columns">
            <div class="primary callout">
              <p>Six columns</p>
            </div>
          </div>
          <div class="large-6 medium-6 columns">
            <div class="primary callout">
              <p>Six columns</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-4 medium-4 small-4 columns">
            <div class="primary callout">
              <p>Four columns</p>
            </div>
          </div>
          <div class="large-4 medium-4 small-4 columns">
            <div class="primary callout">
              <p>Four columns</p>
            </div>
          </div>
          <div class="large-4 medium-4 small-4 columns">
            <div class="primary callout">
              <p>Four columns</p>
            </div>
          </div>
        </div>

        <hr />

        <h5>We bet you&rsquo;ll need a form somewhere:</h5>
        <form>
          <div class="row">
            <div class="large-12 columns">
              <label>Input Label</label>
              <input type="text" placeholder="large-12.columns" />
            </div>
          </div>
          <div class="row">
            <div class="large-4 medium-4 columns">
              <label>Input Label</label>
              <input type="text" placeholder="large-4.columns" />
            </div>
            <div class="large-4 medium-4 columns">
              <label>Input Label</label>
              <input type="text" placeholder="large-4.columns" />
            </div>
            <div class="large-4 medium-4 columns">
              <div class="row collapse">
                <label>Input Label</label>
                <div class="input-group">
                  <input type="text" placeholder="small-9.columns" class="input-group-field" />
                  <span class="input-group-label">.com</span>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns">
              <label>Select Box</label>
              <select>
                <option value="husker">Husker</option>
                <option value="starbuck">Starbuck</option>
                <option value="hotdog">Hot Dog</option>
                <option value="apollo">Apollo</option>
              </select>
            </div>
          </div>
          <div class="row">
            <div class="large-6 medium-6 columns">
              <label>Choose Your Favorite</label>
              <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Radio 1</label>
              <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Radio 2</label>
            </div>
            <div class="large-6 medium-6 columns">
              <label>Check these out</label>
              <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
              <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns">
              <label>Textarea Label</label>
              <textarea placeholder="small-12.columns"></textarea>
            </div>
          </div>
        </form>
      </div>

      <div class="large-4 medium-4 columns">
        <h5>Try one of these buttons:</h5>
        <p><a href="#" class="button">Simple Button</a><br/>
        <a href="#" class="success button">Success Btn</a><br/>
        <a href="#" class="alert button">Alert Btn</a><br/>
        <a href="#" class="secondary button">Secondary Btn</a></p>
        <div class="callout">
          <h5>So many components, girl!</h5>
          <p>A whole kitchen sink of goodies comes with Foundation. Check out the docs to see them all, along with details on making them your own.</p>
          <a href="http://foundation.zurb.com/sites/docs/" class="small button">Go to Foundation Docs</a>
        </div>
      </div>
    </div>
    <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'foundation/js/vendor/what-input.js' %}"></script>
    <script src="{% static 'foundation/js/vendor/foundation.js' %}"></script>
    <script src="{% static 'foundation/js/vendor/app.js' %}"></script>
  </body>
</html>